-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT * P.PRICE) AS SALES FROM OFFLINE_SALE O
    LEFT JOIN PRODUCT P
    ON P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY PRODUCT_CODE
    ORDER BY SALES DESC, PRODUCT_CODE

    