-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.NAME FROM ANIMAL_INS AI 
LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NOT NULL AND AI.DATETIME IS NOT NULL
ORDER BY AO.DATETIME - AI.DATETIME DESC
LIMIT 2