-- 코드를 작성해주세요

SELECT COUNT(*) AS FISH_COUNT, I.FISH_NAME
    FROM FISH_NAME_INFO I
    JOIN FISH_INFO F
        ON I.FISH_TYPE = F.FISH_TYPE
    GROUP BY I.FISH_NAME
    ORDER BY FISH_COUNT DESC



    