-- 코드를 입력하세요
SELECT R.CAR_ID FROM CAR_RENTAL_COMPANY_CAR R
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON R.CAR_ID = H.CAR_ID
WHERE H.START_DATE LIKE '%-10-%' AND R.CAR_TYPE = '세단'
GROUP BY R.CAR_ID
ORDER BY R.CAR_ID DESC