-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES FROM BOOK B 
LEFT JOIN BOOK_SALES BS 
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE <= '2022-01-31'
GROUP BY CATEGORY ORDER BY CATEGORY