SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE
      FROM (SELECT FISH_TYPE, IF (LENGTH IS NULL, 10, LENGTH) LENGTH 
            FROM FISH_INFO) A
      GROUP BY FISH_TYPE
      HAVING AVG(LENGTH) >= 33)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE
